### ISSUE TITLE
Can't get it work :(

### ISSUE THREAD

**Issue by totseans** [conoro/tiktok-rss-flat#27]
2024-01-16 17:53:40,032 Using selector: EpollSelector
2024-01-16 17:55:42,363 Error: Data scraping unable to complete in 60.0s (retries: 3)

Get this error :(

**Comment by conoro** [comment]
Is your repo public so I can have a look? The main library I rely on has to play a game of cat and mouse with TikTok all the time. So we've had long periods where it hasn't worked at all. But I haven't had any issues recently.

**Comment by skyborne99** [comment]
Jumping on this to say I'm getting the same error, my repo url is [https://skyborne99.github.io/tiktok-rss-flat/](https://skyborne99.github.io/tiktok-rss-flat/)

I noticed that the RSS feeds from the original repo are working, however I updated the tiktok usernames in subscriptions.csv over an hour ago, and it still hasn't generated the new feeds in the rss directory, and the old ones from the original repo are still there.

Not sure if it's related, but I also got a notification "pages build and deployment with artifacts-next workflow run cancelled for main branch" with the annotations:

> 1 error and 1 warning
> deploy: Canceling since a higher priority waiting request for 'pages build and deployment with artifacts-next @ main' exists
> build: Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Since the RSS feeds from the original repo are showing up in my RSS reader (Inoreader), it doesn't seem to be an issue with the library?

**Comment by conoro** [comment]
@skyborne99 There are two GitHub Actions workflows. The "flat" one is disabled by default on forks. You just have to enable that for the RSS feeds to be generated.

**Comment by skyborne99** [comment]
@conoro Thanks for the reply! I've enabled the "flat" workflow and can see at the link you sent that it is running each hour now. However, the xml files in my rss directory have still not been updated (they're still the same ones from the original repo)

**Comment by conoro** [comment]
@skyborne99 Looking at the GitHub for the TikTok API that I use, it appears there are some known issues and the author hasn't had time to address them. We'll just have to wait until it's fixed. I think everything will automatically start working again when it's fixed on that side.
