### ISSUE TITLE
How to get updates?

### ISSUE THREAD

**Issue by pukku** [conoro/tiktok-rss-flat#6]
Hi! I'm apparently less useful at git than I thought. Now that I've modified my list of tiktoks, and removed the CNAME file, etc., your repository and mine have gone their separate ways for a bit. But I notice that you've made some changes that I should pull over (update to new version of OCTO). How do I tell GitHub to pull over that one commit? Is there something that I should be googling for? Did I set up my project incorrectly (should I have cloned yours, the made my changes in a branch, so I could just "rebase"(?) on yours)?

Thanks for any suggestions,
Ricky

**Comment by conoro** [comment]
Hey @pukku , I'm afraid I'm even worse at Git than you. I'm a strong believer in how XKCD handles it: https://m.xkcd.com/1597/

It's my fault really. I shouldn't have my personal settings in the repo. I should have some example config files which you copy, rename and edit. Then you can easily just merge over any core changes I make into your own fork.

But since I've made this mess, TBH the easiest way to do things right now is to clone the latest code from this repo into another local directory and copy over the flat.yml file from there.

I'll see if I can clean things up to make it easier in the future.

**Comment by pukku** [comment]
Thanks! I'll do that...
